const LS={tasks:'studyflow_tasks',subjects:'studyflow_subjects',theme:'studyflow_theme',timer:'studyflow_timer',pomo:'studyflow_pomo_settings',sidebar:'studyflow_sidebar'};
const lsGet=k=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):null;}catch{return null;}};
const lsSet=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const $=id=>document.getElementById(id);
const $$=sel=>document.querySelectorAll(sel);
const escHtml=s=>{const e=document.createElement('div');e.appendChild(document.createTextNode(s));return e.innerHTML;};
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1);
const pIcon=p=>p==='high'?'🔴':p==='medium'?'🟡':'🟢';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const fmtTime=s=>String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
const fmtDueTime=s=>{if(!s)return'';const[h,m]=s.split(':').map(Number);return`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`;};
const fmtRemLabel=m=>!m?'':m<60?m+'min before':m===60?'1hr before':m===1440?'1 day before':(m/60)+'hr before';
const fmtDate=due=>{if(!due)return'';const d=new Date(due+'T00:00:00');if(isNaN(d))return due;const t=new Date();t.setHours(0,0,0,0);const df=Math.round((d-t)/86400000);return df===0?'Due today':df===1?'Due tomorrow':df===-1?'Due yesterday':df<0?`${Math.abs(df)}d overdue`:df<7?`In ${df} days`:d.toLocaleDateString('en-GB',{day:'numeric',month:'short'});};
function showToast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;$('toast-container').appendChild(t);setTimeout(()=>t.remove(),2500);}

// State
let tasks=[],activeFilter='all',activeTab='general',subjects=[],activeSubject=null;
const saveTasks=()=>lsSet(LS.tasks,tasks),loadTasks=()=>{tasks=lsGet(LS.tasks)||[];};
const saveSubjects=()=>lsSet(LS.subjects,subjects),loadSubjects=()=>{subjects=lsGet(LS.subjects)||[];};

// Sidebar & Sections
const sidebarState={pomodoro:true,quote:true};
function toggleSidebar(){const s=$('sidebar'),b=$('sidebar-backdrop');if(s&&b){s.classList.toggle('open');b.classList.toggle('open');}}
function saveSidebarState(){lsSet(LS.sidebar,sidebarState);}
function loadSidebarState(){const s=lsGet(LS.sidebar);if(s){sidebarState.pomodoro=s.pomodoro??true;sidebarState.quote=s.quote??true;}['pomodoro','quote'].forEach(k=>{const el=$('section-'+k);if(el)el.classList.toggle('collapsed',!sidebarState[k]);});}
function toggleSection(id){sidebarState[id]=!sidebarState[id];saveSidebarState();['pomodoro','quote'].forEach(k=>{const el=$('section-'+k);if(el)el.classList.toggle('collapsed',!sidebarState[k]);});}

// Subjects
function switchTab(tab){activeTab=tab;$('tab-general').classList.toggle('active',tab==='general');$('tab-study').classList.toggle('active',tab==='study');$('subject-folders').style.display=tab==='study'?'flex':'none';if(tab==='study'&&subjects.length&&!activeSubject)activeSubject=subjects[0];renderSubjects();renderTasks();}
function renderSubjects(){const c=$('subject-folders');c.innerHTML='';subjects.forEach(sub=>{const btn=document.createElement('button');btn.className='folder-btn'+(activeSubject===sub?' active':'');const sp=document.createElement('span');sp.textContent='📁 '+sub;const del=document.createElement('span');del.innerHTML='&#x2715;';del.style.cssText='margin-left:.4rem;opacity:.5;font-size:.75rem';del.title='Delete Subject';del.onmouseover=()=>del.style.opacity='1';del.onmouseout=()=>del.style.opacity='.5';del.onclick=e=>{e.stopPropagation();if(confirm(`Delete subject "${sub}" and all its tasks?`))deleteSubject(sub);};btn.appendChild(sp);btn.appendChild(del);btn.onclick=()=>{activeSubject=sub;renderSubjects();renderTasks();};c.appendChild(btn);});const a=document.createElement('button');a.className='add-folder-btn';a.textContent='+ New Subject';a.onclick=promptAddSubject;c.appendChild(a);}
function promptAddSubject(){const n=prompt('Enter subject name:');if(n?.trim()){const s=n.trim();if(!subjects.includes(s)){subjects.push(s);saveSubjects();}activeSubject=s;renderSubjects();renderTasks();}}
function deleteSubject(sub){subjects=subjects.filter(s=>s!==sub);saveSubjects();const pl=tasks.length;tasks=tasks.filter(t=>!(t.taskType==='study'&&t.subject===sub));if(tasks.length!==pl)saveTasks();if(activeSubject===sub)activeSubject=subjects[0]||null;renderSubjects();renderTasks();showToast('🗑 Subject deleted');}

// Task CRUD
function addTask(title,desc,due,priority,dueTime,rm){const t={id:uid(),title:title.trim(),desc:desc.trim(),due,dueTime:dueTime||null,reminderMins:rm?+rm:null,priority,done:false,createdAt:Date.now(),taskType:activeTab,subject:activeTab==='study'?activeSubject:null};tasks.unshift(t);saveTasks();scheduleReminder(t);return t;}
function updateTask(id,title,desc,due,priority,dueTime,rm){tasks=tasks.map(t=>t.id===id?{...t,title:title.trim(),desc:desc.trim(),due,priority,dueTime:dueTime||null,reminderMins:rm?+rm:null}:t);saveTasks();const t=tasks.find(t=>t.id===id);if(t)scheduleReminder(t);}
function deleteTask(id){if(reminderTimeouts[id]){clearTimeout(reminderTimeouts[id]);delete reminderTimeouts[id];}tasks=tasks.filter(t=>t.id!==id);saveTasks();}
function toggleDone(id){tasks=tasks.map(t=>t.id===id?{...t,done:!t.done}:t);saveTasks();const t=tasks.find(t=>t.id===id);if(t?.done&&reminderTimeouts[id]){clearTimeout(reminderTimeouts[id]);delete reminderTimeouts[id];}}

// Filter / Sort / Render
function setFilter(f){activeFilter=f;$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderTasks();if(window.innerWidth<=768){const s=$('sidebar'),b=$('sidebar-backdrop');if(s)s.classList.remove('open');if(b)b.classList.remove('open');}}
function getFilteredTasks(){const q=$('search-input').value.trim().toLowerCase();return tasks.filter(t=>{const ms=!q||(t.title||'').toLowerCase().includes(q)||(t.desc||'').toLowerCase().includes(q);const fm={pending:!t.done,completed:t.done,high:t.priority==='high',medium:t.priority==='medium',low:t.priority==='low'};const mf=activeFilter==='all'||fm[activeFilter];const tp=t.taskType||'general';const mt=activeTab==='general'?tp==='general':(tp==='study'&&t.subject===activeSubject);return ms&&mf&&mt;});}
function getSortedTasks(arr){const m=$('sort-select').value,p={high:0,medium:1,low:2};return[...arr].sort((a,b)=>m==='date-asc'?new Date(a.due)-new Date(b.due):m==='date-desc'?new Date(b.due)-new Date(a.due):m==='priority-desc'?p[a.priority]-p[b.priority]:m==='priority-asc'?p[b.priority]-p[a.priority]:m==='created'?b.createdAt-a.createdAt:0);}
function createTaskCard(t){const card=document.createElement('div');card.className='task-card'+(t.done?' done':'');card.dataset.priority=t.priority;card.dataset.id=t.id;const due=t.due?new Date(t.due+'T00:00:00'):null,today=new Date();today.setHours(0,0,0,0);const ov=due&&due<today&&!t.done;card.innerHTML=`<div class="task-top"><div class="task-checkbox${t.done?' checked':''}" onclick="handleToggleDone('${t.id}')" title="${t.done?'Mark pending':'Mark done'}"></div><div class="task-title">${escHtml(t.title)}</div></div>${t.desc?`<div class="task-desc">${escHtml(t.desc)}</div>`:''}<div class="task-meta"><span class="badge badge-${t.priority}">${pIcon(t.priority)} ${cap(t.priority)}</span>${t.due?`<span class="badge ${ov?'badge-overdue':'badge-date'}">📅 ${fmtDate(t.due)}${t.dueTime?' · '+fmtDueTime(t.dueTime):''}</span>`:''} ${t.reminderMins&&!t.done?`<span class="badge badge-date">🔔 ${fmtRemLabel(t.reminderMins)}</span>`:''}</div><div class="task-actions"><button class="action-btn" onclick="openModal('${t.id}')">✎ Edit</button><button class="action-btn delete" onclick="handleDelete('${t.id}')">🗑 Delete</button></div>`;return card;}
function renderTasks(){const grid=$('task-grid');grid.innerHTML='';const mt=$('main-title');if(mt)mt.innerHTML=activeTab==='general'?'General <em>Tasks</em>':(activeSubject?`${escHtml(activeSubject)} <em>Tasks</em>`:'Study <em>Tasks</em>');const fl=getSortedTasks(getFilteredTasks());if(!fl.length){let em=activeFilter==='all'?'No tasks yet':'Nothing here',sm=activeFilter==='all'?'Click "Add Task" to get started!':'Try a different filter.';if(activeTab==='study'&&!activeSubject){em='No subject selected';sm='Create a subject to add tasks.';}grid.innerHTML=`<div class="empty-state" style="grid-column:1/-1"><div class="big-icon">📚</div><h3>${em}</h3><p>${sm}</p></div>`;}else{const f=document.createDocumentFragment();fl.forEach(t=>f.appendChild(createTaskCard(t)));grid.appendChild(f);}renderStats();}
function renderStats(){const tt=tasks.filter(t=>{const tp=t.taskType||'general';return activeTab==='general'?tp==='general':(tp==='study'&&t.subject===activeSubject);});const total=tt.length,done=tt.filter(t=>t.done).length,pend=total-done;$('stat-done').textContent=done;$('stat-pending').textContent=pend;$('stat-high').textContent=tt.filter(t=>t.priority==='high'&&!t.done).length;$('progress-bar').style.width=(total?Math.round(done/total*100):0)+'%';$('progress-label').textContent=`${done} of ${total} done`;$('count-all').textContent=total;$('count-pending').textContent=pend;$('count-completed').textContent=done;['high','medium','low'].forEach(p=>$('count-'+p).textContent=tt.filter(t=>t.priority===p).length);if(typeof refreshActiveTaskHighlight==='function')refreshActiveTaskHighlight();}

// Event Handlers
function handleToggleDone(id){toggleDone(id);renderTasks();const t=tasks.find(t=>t.id===id);if(t?.done){showToast('✓ Task completed!');sendNotification('✅ Task Complete!',t.title+' marked as done. Great work!','✅');}else showToast('↩ Marked as pending');}
function handleDelete(id){const t=tasks.find(t=>t.id===id);if(!t||!confirm(`Delete "${t.title}"?`))return;deleteTask(id);renderTasks();showToast('🗑 Task deleted');}
function handleFormSubmit(e){e.preventDefault();const g=id=>$(id).value,title=g('task-title'),desc=g('task-desc'),due=g('task-due'),priority=g('task-priority'),dueTime=g('task-due-time'),rm=g('task-reminder'),editId=g('edit-id');if(!title.trim()){$('task-title').focus();return;}if(!due){$('task-due').focus();return;}if(editId){updateTask(editId,title,desc,due,priority,dueTime,rm);showToast('✏️ Task updated');}else{addTask(title,desc,due,priority,dueTime,rm);showToast('✅ Task added');}closeModal();renderTasks();}

// Modal
function openModal(editId=null){if(!editId&&activeTab==='study'&&!activeSubject){alert('Please create or select a subject folder first.');return;}$('task-form').reset();$('edit-id').value='';$('modal-title-el').textContent='Add Task';$('form-submit-btn').textContent='Add Task';if(editId){const t=tasks.find(t=>t.id===editId);if(!t)return;['id','title','desc','due','priority','dueTime','reminderMins'].forEach(k=>{const el=$('task-'+{id:'edit-id',title:'title',desc:'desc',due:'due',dueTime:'due-time',reminderMins:'reminder'}[k]||'task-'+k);if(el)el.value=t[k]||'';});$('edit-id').value=t.id;$('task-priority').value=t.priority||'medium';$('task-reminder').value=t.reminderMins?String(t.reminderMins):'';$('modal-title-el').textContent='Edit Task';$('form-submit-btn').textContent='Save Changes';}else $('task-due').value=new Date().toISOString().split('T')[0];updateDatetimePreview();updateChipsFromInputs();checkNotifPermissionBanner();$('modal-overlay').classList.add('open');$('task-title').focus();}
function closeModal(){$('modal-overlay').classList.remove('open');}
function handleOverlayClick(e){if(e.target===$('modal-overlay'))closeModal();}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});

// Quotes
const FQ=[{content:"The secret of getting ahead is getting started.",author:"Mark Twain"},{content:"You don't have to be great to start, but you have to start to be great.",author:"Zig Ziglar"},{content:"Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.",author:"Richard Feynman"},{content:"Success is the sum of small efforts, repeated day in and day out.",author:"Robert Collier"},{content:"The expert in anything was once a beginner.",author:"Helen Hayes"},{content:"Education is not the filling of a bucket, but the lighting of a fire.",author:"W.B. Yeats"}];
async function fetchQuote(){const te=$('quote-text'),ae=$('quote-author');te.className='quote-loading';te.textContent='Fetching wisdom…';ae.textContent='';try{const r=await fetch('https://api.quotable.io/random?tags=education%7Cinspirational%7Cmotivational&maxLength=120');if(!r.ok)throw 0;const d=await r.json();te.className='';te.textContent=`"${d.content}"`;ae.textContent=`— ${d.author}`;}catch{const q=FQ[Math.random()*FQ.length|0];te.className='';te.textContent=`"${q.content}"`;ae.textContent=`— ${q.author}`;}}

// Theme
function initTheme(){const s=localStorage.getItem(LS.theme)||'light';document.documentElement.setAttribute('data-theme',s);$('theme-btn').textContent=s==='dark'?'☀':'🌙';}
$('theme-btn').addEventListener('click',()=>{const n=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',n);localStorage.setItem(LS.theme,n);$('theme-btn').textContent=n==='dark'?'☀':'🌙';});
$('search-input').addEventListener('input',renderTasks);

// Pomodoro Timer
const timerState={mode:'focus',timeLeft:1500,isRunning:false,sessions:0,activeTaskId:null};
let pomoSettings={focusDuration:25,breakDuration:5},timerInterval=null;
const saveTimerState=()=>lsSet(LS.timer,timerState);
const savePomoSettings=()=>lsSet(LS.pomo,pomoSettings);
function loadPomoSettings(){const s=lsGet(LS.pomo);if(s)pomoSettings={...pomoSettings,...s};}
function loadTimerState(){const s=lsGet(LS.timer);if(!s)return;timerState.mode=s.mode||'focus';timerState.timeLeft=s.timeLeft??getCurrentDuration();timerState.isRunning=false;timerState.sessions=s.sessions||0;timerState.activeTaskId=s.activeTaskId||null;}
function getActiveTimerTask(){const p=tasks.filter(t=>!t.done);return(timerState.activeTaskId&&p.find(t=>t.id===timerState.activeTaskId))||p[0]||null;}
function getCurrentDuration(){if(timerState.mode==='break')return pomoSettings.breakDuration*60;const t=getActiveTimerTask();return(t?.customFocusTime||pomoSettings.focusDuration)*60;}
function updateTimerDisplay(){const total=getCurrentDuration(),pct=total?timerState.timeLeft/total*100:0;$('pomo-time').textContent=fmtTime(timerState.timeLeft);$('pomo-mode-badge').textContent=timerState.mode==='focus'?'Focus':'Break';$('pomodoro-card').setAttribute('data-pmode',timerState.mode);$('pomo-ring-fill').style.width=Math.min(100,Math.max(0,pct))+'%';$('pomo-start-btn').style.display=timerState.isRunning?'none':'';$('pomo-pause-btn').style.display=timerState.isRunning?'':'none';if(!timerState.isRunning)$('pomo-start-btn').textContent=timerState.timeLeft>=total?'▶ Start':'▶ Resume';$('pomo-session-count').textContent=timerState.sessions;refreshActiveTaskHighlight();}
function refreshActiveTaskHighlight(){const t=getActiveTimerTask(),strip=$('pomo-active-task'),nameEl=$('pomo-task-name');if(timerState.mode==='focus'&&t){nameEl.textContent=t.title+(t.customFocusTime?` (${t.customFocusTime}m)`:'');strip.classList.add('visible');}else strip.classList.remove('visible');}
function startTimer(){if(timerState.isRunning)return;timerState.isRunning=true;saveTimerState();updateTimerDisplay();timerInterval=setInterval(()=>{timerState.timeLeft--;if(timerState.timeLeft<=0){clearInterval(timerInterval);timerInterval=null;timerState.isRunning=false;onTimerEnd();}else{saveTimerState();updateTimerDisplay();}},1000);}
function pauseTimer(){if(!timerState.isRunning)return;clearInterval(timerInterval);timerInterval=null;timerState.isRunning=false;saveTimerState();updateTimerDisplay();showToast('⏸ Timer paused');}
function resetTimer(){clearInterval(timerInterval);timerInterval=null;timerState.isRunning=false;timerState.mode='focus';timerState.timeLeft=getCurrentDuration();saveTimerState();updateTimerDisplay();showToast('🔄 Timer reset');}
function switchMode(){timerState.mode=timerState.mode==='focus'?'break':'focus';timerState.timeLeft=getCurrentDuration();timerState.isRunning=false;saveTimerState();updateTimerDisplay();}
function onTimerEnd(){const msg=timerState.mode==='focus'?'🎉 Focus session complete! Time for a break.':'☕ Break over — back to work!';if(timerState.mode==='focus'){timerState.sessions++;saveTimerState();}showToast(msg);setTimeout(()=>alert(msg.replace(/^[^ ]+ /,'')),50);updateTimerDisplay();switchMode();}

// Pomo Settings Modal
function openPomoSettings(){$('global-focus-time').value=pomoSettings.focusDuration;$('global-break-time').value=pomoSettings.breakDuration;const sel=$('pomo-active-task-select');sel.innerHTML='<option value="">-- No specific task (Use next pending) --</option>';tasks.filter(t=>!t.done).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.title;sel.appendChild(o);});const at=getActiveTimerTask();sel.value=(at&&timerState.activeTaskId===at.id)?at.id:'';$('custom-focus-time').value=(at&&timerState.activeTaskId===at.id)?at.customFocusTime||'':'';sel.onchange=e=>{const t=tasks.find(x=>x.id===e.target.value);$('custom-focus-time').value=t?.customFocusTime||'';};$('pomo-settings-overlay').classList.add('open');}
function closePomoSettings(){$('pomo-settings-overlay').classList.remove('open');}
function handlePomoOverlayClick(e){if(e.target===$('pomo-settings-overlay'))closePomoSettings();}
function resetPomoDefaults(){$('global-focus-time').value=25;$('global-break-time').value=5;$('pomo-active-task-select').value='';$('custom-focus-time').value='';}
function handlePomoSettingsSubmit(e){e.preventDefault();const ft=+$('global-focus-time').value,bt=+$('global-break-time').value;if(!ft||ft<1){$('global-focus-time').focus();return;}if(!bt||bt<1){$('global-break-time').focus();return;}pomoSettings.focusDuration=ft;pomoSettings.breakDuration=bt;savePomoSettings();const taskId=$('pomo-active-task-select').value,cf=+$('custom-focus-time').value;timerState.activeTaskId=taskId||null;saveTimerState();if(taskId){tasks=tasks.map(t=>t.id===taskId?{...t,customFocusTime:(cf&&cf>=1)?cf:null}:t);saveTasks();renderTasks();}const nd=getCurrentDuration();timerState.timeLeft=timerState.isRunning?Math.min(timerState.timeLeft,nd):nd;saveTimerState();updateTimerDisplay();closePomoSettings();showToast('⚙️ Timer settings saved');}

// Notifications
const reminderTimeouts={};
function requestNotifPermission(){if(!('Notification'in window))return;Notification.requestPermission().then(p=>{checkNotifPermissionBanner();if(p==='granted')showToast('🔔 Notifications enabled!');});}
function checkNotifPermissionBanner(){const b=$('notif-permission-banner');if(!b)return;b.style.display=(!('Notification'in window)||Notification.permission==='granted'||!$('task-reminder')?.value)?'none':'flex';}
async function sendNotification(title,body,icon){if(!('Notification'in window)||Notification.permission!=='granted')return;try{if('serviceWorker'in navigator){const r=await navigator.serviceWorker.getRegistration();if(r){r.showNotification(title,{body,icon:icon||'📚',badge:'📚',vibrate:[100,50,100],tag:'studyflow-'+Date.now()});return;}}const n=new Notification(title,{body,icon:icon||'📚',badge:'📚',tag:'studyflow-'+Date.now()});setTimeout(()=>n.close(),8000);}catch(e){console.error(e);}}
function scheduleReminder(task){if(reminderTimeouts[task.id]){clearTimeout(reminderTimeouts[task.id]);delete reminderTimeouts[task.id];}if(task.done||!task.due||!task.dueTime||!task.reminderMins)return;const due=new Date(task.due+'T'+task.dueTime);if(isNaN(due))return;const ms=due-task.reminderMins*60000-Date.now();if(ms<=0||ms>2147483647)return;reminderTimeouts[task.id]=setTimeout(()=>{delete reminderTimeouts[task.id];const live=tasks.find(t=>t.id===task.id);if(!live||live.done)return;sendNotification('⏰ Reminder: '+live.title,`Due in ${fmtRemLabel(live.reminderMins)} at ${fmtDueTime(live.dueTime)}. Don't forget!`,'⏰');showToast('⏰ Reminder: '+live.title);},ms);}
const rescheduleAllReminders=()=>tasks.forEach(t=>{if(!t.done)scheduleReminder(t);});
document.addEventListener('change',e=>{if(e.target?.id==='task-reminder')checkNotifPermissionBanner();});

// Datetime Chips
function setupDatetimeChips(){const di=$('task-due'),ti=$('task-due-time'),upd=()=>{updateDatetimePreview();updateChipsFromInputs();};$$('.date-chip[data-date]').forEach(c=>c.addEventListener('click',()=>{const d=new Date();if(c.dataset.date==='tomorrow')d.setDate(d.getDate()+1);if(c.dataset.date==='next-week')d.setDate(d.getDate()+7);di.value=d.toISOString().split('T')[0];upd();}));$$('.time-chip[data-time]').forEach(c=>c.addEventListener('click',()=>{ti.value=c.dataset.time;upd();}));$('custom-date-btn').addEventListener('click',()=>{try{di.showPicker();}catch{di.focus();}});$('custom-time-btn').addEventListener('click',()=>{try{ti.showPicker();}catch{ti.focus();}});di.addEventListener('change',upd);ti.addEventListener('change',upd);}
function updateDatetimePreview(){const d=$('task-due').value,t=$('task-due-time').value;$('preview-date').textContent=d?fmtDate(d):'No date';$('preview-time').textContent=t?' at '+fmtDueTime(t):'';}
function updateChipsFromInputs(){const dv=$('task-due').value,tv=$('task-due-time').value,td=new Date(),tmrw=new Date(+td+864e5),nw=new Date(+td+6048e5);const dm={[td.toISOString().split('T')[0]]:'today',[tmrw.toISOString().split('T')[0]]:'tomorrow',[nw.toISOString().split('T')[0]]:'next-week'};$$('.date-chip').forEach(c=>c.classList.remove('active'));const key=dm[dv];if(key)document.querySelector(`.date-chip[data-date="${key}"]`)?.classList.add('active');else if(dv)$('custom-date-btn').classList.add('active');$$('.time-chip').forEach(c=>c.classList.remove('active'));if(tv){const mc=document.querySelector(`.time-chip[data-time="${tv}"]`);if(mc)mc.classList.add('active');else $('custom-time-btn').classList.add('active');}}

// Init
(function(){loadSidebarState();loadTasks();loadSubjects();initTheme();switchTab('general');fetchQuote();loadPomoSettings();loadTimerState();updateTimerDisplay();rescheduleAllReminders();setupDatetimeChips();})();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(e=>console.log('SW failed:',e)));
